### PR TITLE
Fixed dice.pl

### PR DESCRIPTION
**Pull request by tadzik**
pick :replace is now .roll

### CODE REVIEW

**Comment by colomon** [comment]
The problem with this is that (at least in theory) the scripts are supposed to run on older versions of Rakudo as well as the current versions.  Did the first R\* release have .roll?

**Comment by colomon** [comment]
Whoops, didn't mean to close that.  Still not quite used to this interface.

**Comment by nunorc** [comment]
Right, for example, for rakudo-star-2010.07:

Method 'roll' not found for invocant of class 'Range'

**Comment by colomon** [comment]
smashz, it seems like we might need some sort of meta-data that would allow us to select different versions of the source code for different Rakudos.  Could you make the benchmark testing code available so we can take a stab at implementing that?  (Not to mention let the rest of us run the code at home?)

Thanks!

**Comment by tadzik** [comment]
Well, we can always either try{}, or use $*PERL<version> in the beginning of the script

**Comment by nunorc** [comment]
@colomon sure, i'll make the scripts available has soon has i have some time, but don't expect anything fancy

**Pull request closed without merging**
